steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    
  # Run tests
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']
    env:
      - 'NODE_ENV=test'
    
  # Build application
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/flashfusion-unified:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/flashfusion-unified:latest',
      '.'
    ]
    
  # Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flashfusion-unified:$COMMIT_SHA']
    
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/flashfusion-unified:latest']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'flashfusion-unified',
      '--image', 'gcr.io/$PROJECT_ID/flashfusion-unified:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--memory', '2Gi',
      '--cpu', '2',
      '--min-instances', '0',
      '--max-instances', '10',
      '--concurrency', '100',
      '--timeout', '900'
    ]
    
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: '1200s'

substitutions:
  _SERVICE_NAME: 'flashfusion-unified'
  _REGION: 'us-central1'