name: Auto Commit Changes

on:
  # Run every hour
  schedule:
    - cron: '0 * * * *'
  
  # Allow manual trigger
  workflow_dispatch:
  
  # Trigger on push to main (for immediate processing)
  push:
    branches: [ main ]

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action Auto-Commit"

    - name: Check for changes
      id: verify-changed-files
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changed=true" >> $GITHUB_OUTPUT
        else
          echo "changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Auto-commit changes
      if: steps.verify-changed-files.outputs.changed == 'true'
      run: |
        git add -A
        git commit -m "Auto-commit: $(date '+%Y-%m-%d %H:%M:%S UTC')" || exit 0
        git push